version: '2'
services:
  web:
    build: .
    ports:
     - "3333:5000"
    environment:
      - VIRTUAL_HOST=week3-pp.piti.me
      - LETSENCRYPT_HOST=week3-pp.piti.me
      - LETSENCRYPT_EMAIL=piti118@gmail.com
    network_mode: "bridge"

    
